apiVersion: v1
kind: Pod
metadata:
  name: sol-bot
  labels:
    app: sol-bot
spec:
  containers:
    - name: k8s-sol-bot
      image: pavangudiwada/buildxtest2:latest
      ports:
        - containerPort: 5000
          protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
  nodeSelector:
    "beta.kubernetes.io/arch": arm64
