apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bot-replicaset
  labels:
    app: bot-app-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bot-app-replicaset
  template:
    metadata:
      labels:
        app: bot-app-replicaset
    spec:
      containers:
        - name: bot-app
          image: pavangudiwada/buildxtest2:latest
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    app: meme-app-replicaset
