// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package attendance

import dbgen "github.com/sol-armada/sol-bot/database/sqlc/dbgen"

type ConverterImpl struct{}

func (c *ConverterImpl) FromDbAttendanceRow(source dbgen.Attendance) *Attendance {
	var attendanceAttendance Attendance
	attendanceAttendance.Id = source.ID
	attendanceAttendance.Name = source.Name
	attendanceAttendance.SubmittedBy = ConvertSubmittedByToMember(source.SubmittedBy)
	attendanceAttendance.Recorded = source.Recorded
	attendanceAttendance.Successful = source.Successful
	attendanceAttendance.Tokenable = source.Tokenable
	attendanceAttendance.Status = Status(source.Status)
	attendanceAttendance.ChannelId = source.ChannelID
	attendanceAttendance.MessageId = source.MessageID
	attendanceAttendance.DateCreated = PgTypeTimestamptzToTime(source.DateCreated)
	attendanceAttendance.DateUpdated = PgTypeTimestamptzToTime(source.DateUpdated)
	return &attendanceAttendance
}
func (c *ConverterImpl) FromDbAttendanceRows(source []dbgen.Attendance) []*Attendance {
	var pAttendanceAttendanceList []*Attendance
	if source != nil {
		pAttendanceAttendanceList = make([]*Attendance, len(source))
		for i := 0; i < len(source); i++ {
			pAttendanceAttendanceList[i] = c.FromDbAttendanceRow(source[i])
		}
	}
	return pAttendanceAttendanceList
}
func (c *ConverterImpl) FromDbParticipantRow(source dbgen.AttendanceParticipant) *Participant {
	var attendanceParticipant Participant
	attendanceParticipant.Member = ConvertMemberIdToMember(source.MemberID)
	attendanceParticipant.JoinedAtStart = source.JoinedAtStart
	attendanceParticipant.StayedUntilEnd = source.StayedUntilEnd
	attendanceParticipant.IsManager = source.IsManager
	return &attendanceParticipant
}
func (c *ConverterImpl) FromDbParticipantRows(source []dbgen.AttendanceParticipant) []*Participant {
	var pAttendanceParticipantList []*Participant
	if source != nil {
		pAttendanceParticipantList = make([]*Participant, len(source))
		for i := 0; i < len(source); i++ {
			pAttendanceParticipantList[i] = c.FromDbParticipantRow(source[i])
		}
	}
	return pAttendanceParticipantList
}
