DROP TABLE IF EXISTS raffles;
DROP TABLE IF EXISTS giveaways;
DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS attendance_participants;
DROP TABLE IF EXISTS attendance_payouts;
DROP TABLE IF EXISTS attendance;
DROP TABLE IF EXISTS member_blueprints;
DROP TABLE IF EXISTS members;
