package dbnotify

import (
	"encoding/json"
	"fmt"
	"time"
)

type OperationType string

const (
	Insert OperationType = "INSERT"
	Update OperationType = "UPDATE"
	Delete OperationType = "DELETE"
)

// Event is one decoded payload emitted by trigger-backed pg_notify calls
type Event struct {
	Channel        Channel        `json:"-"`
	PayloadVersion int            `json:"payload_version"`
	Operation      OperationType  `json:"operation"`
	Schema         string         `json:"schema"`
	Table          string         `json:"table"`
	PrimaryKey     map[string]any `json:"primary_key"`
	OccurredAt     time.Time      `json:"occurred_at"`
	ChangedColumns []string       `json:"changed_columns"`
	OldValues      map[string]any `json:"old_values"`
	NewValues      map[string]any `json:"new_values"`
	RawPayload     string         `json:"-"`
}

// ParseEvent decodes a NOTIFY payload generated by notify_domain_change
func ParseEvent(channel Channel, payload string) (Event, error) {
	event := Event{Channel: channel, RawPayload: payload}
	if err := json.Unmarshal([]byte(payload), &event); err != nil {
		return Event{}, fmt.Errorf("decode notification payload: %w", err)
	}

	if event.Operation == "" {
		return Event{}, fmt.Errorf("decode notification payload: missing operation")
	}
	if event.Table == "" {
		return Event{}, fmt.Errorf("decode notification payload: missing table")
	}
	if event.PrimaryKey == nil {
		event.PrimaryKey = map[string]any{}
	}
	if event.ChangedColumns == nil {
		event.ChangedColumns = []string{}
	}
	if event.OldValues == nil {
		event.OldValues = map[string]any{}
	}
	if event.NewValues == nil {
		event.NewValues = map[string]any{}
	}

	return event, nil
}
