// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package members

import (
	pgtype "github.com/jackc/pgx/v5/pgtype"
	dbgen "github.com/sol-armada/sol-bot/database/sqlc/dbgen"
	"time"
)

type ConverterImpl struct{}

func (c *ConverterImpl) FromGetMemberRow(source dbgen.GetMemberRow) Member {
	var membersMember Member
	membersMember.Id = source.ID
	membersMember.Name = source.Name
	membersMember.Rank = ConvertRank(source.Rank)
	membersMember.Updated = PgTypeTimestamptzToTime(source.Updated)
	membersMember.Joined = PgTypeTimestamptzToTime(source.Joined)
	membersMember.DmOptOut = source.DmOptOut
	membersMember.DateLeft = c.pgtypeTimestamptzToPTimeTime(source.DateLeft)
	membersMember.IsBot = source.IsBot
	membersMember.IsAlly = source.IsAlly
	membersMember.IsAffiliate = source.IsAffiliate
	membersMember.IsGuest = source.IsGuest
	return membersMember
}
func (c *ConverterImpl) FromGetMemberRows(source []dbgen.GetMemberRow) []Member {
	var membersMemberList []Member
	if source != nil {
		membersMemberList = make([]Member, len(source))
		for i := 0; i < len(source); i++ {
			membersMemberList[i] = c.FromGetMemberRow(source[i])
		}
	}
	return membersMemberList
}
func (c *ConverterImpl) FromListMembersByBlueprintRow(source dbgen.ListMembersByBlueprintRow) Member {
	var membersMember Member
	membersMember.Id = source.ID
	membersMember.Name = source.Name
	membersMember.Rank = ConvertRank(source.Rank)
	membersMember.Updated = PgTypeTimestamptzToTime(source.Updated)
	membersMember.Joined = PgTypeTimestamptzToTime(source.Joined)
	membersMember.DmOptOut = source.DmOptOut
	membersMember.DateLeft = c.pgtypeTimestamptzToPTimeTime(source.DateLeft)
	membersMember.IsBot = source.IsBot
	membersMember.IsAlly = source.IsAlly
	membersMember.IsAffiliate = source.IsAffiliate
	membersMember.IsGuest = source.IsGuest
	return membersMember
}
func (c *ConverterImpl) FromListMembersByBlueprintRows(source []dbgen.ListMembersByBlueprintRow) []Member {
	var membersMemberList []Member
	if source != nil {
		membersMemberList = make([]Member, len(source))
		for i := 0; i < len(source); i++ {
			membersMemberList[i] = c.FromListMembersByBlueprintRow(source[i])
		}
	}
	return membersMemberList
}
func (c *ConverterImpl) FromListMembersByIDsRow(source dbgen.ListMembersByIDsRow) Member {
	var membersMember Member
	membersMember.Id = source.ID
	membersMember.Name = source.Name
	membersMember.Rank = ConvertRank(source.Rank)
	membersMember.Updated = PgTypeTimestamptzToTime(source.Updated)
	membersMember.Joined = PgTypeTimestamptzToTime(source.Joined)
	membersMember.DmOptOut = source.DmOptOut
	membersMember.DateLeft = c.pgtypeTimestamptzToPTimeTime(source.DateLeft)
	membersMember.IsBot = source.IsBot
	membersMember.IsAlly = source.IsAlly
	membersMember.IsAffiliate = source.IsAffiliate
	membersMember.IsGuest = source.IsGuest
	return membersMember
}
func (c *ConverterImpl) FromListMembersByIDsRows(source []dbgen.ListMembersByIDsRow) []Member {
	var membersMemberList []Member
	if source != nil {
		membersMemberList = make([]Member, len(source))
		for i := 0; i < len(source); i++ {
			membersMemberList[i] = c.FromListMembersByIDsRow(source[i])
		}
	}
	return membersMemberList
}
func (c *ConverterImpl) FromListMembersPageRow(source dbgen.ListMembersPageRow) Member {
	var membersMember Member
	membersMember.Id = source.ID
	membersMember.Name = source.Name
	membersMember.Rank = ConvertRank(source.Rank)
	membersMember.Updated = PgTypeTimestamptzToTime(source.Updated)
	membersMember.Joined = PgTypeTimestamptzToTime(source.Joined)
	membersMember.DmOptOut = source.DmOptOut
	membersMember.DateLeft = c.pgtypeTimestamptzToPTimeTime(source.DateLeft)
	membersMember.IsBot = source.IsBot
	membersMember.IsAlly = source.IsAlly
	membersMember.IsAffiliate = source.IsAffiliate
	membersMember.IsGuest = source.IsGuest
	return membersMember
}
func (c *ConverterImpl) FromListMembersPageRows(source []dbgen.ListMembersPageRow) []Member {
	var membersMemberList []Member
	if source != nil {
		membersMemberList = make([]Member, len(source))
		for i := 0; i < len(source); i++ {
			membersMemberList[i] = c.FromListMembersPageRow(source[i])
		}
	}
	return membersMemberList
}
func (c *ConverterImpl) FromListRandomMembersByRankRow(source dbgen.ListRandomMembersByRankRow) Member {
	var membersMember Member
	membersMember.Id = source.ID
	membersMember.Name = source.Name
	membersMember.Rank = ConvertRank(source.Rank)
	membersMember.Updated = PgTypeTimestamptzToTime(source.Updated)
	membersMember.Joined = PgTypeTimestamptzToTime(source.Joined)
	membersMember.DmOptOut = source.DmOptOut
	membersMember.DateLeft = c.pgtypeTimestamptzToPTimeTime(source.DateLeft)
	membersMember.IsBot = source.IsBot
	membersMember.IsAlly = source.IsAlly
	membersMember.IsAffiliate = source.IsAffiliate
	membersMember.IsGuest = source.IsGuest
	return membersMember
}
func (c *ConverterImpl) FromListRandomMembersByRankRows(source []dbgen.ListRandomMembersByRankRow) []Member {
	var membersMemberList []Member
	if source != nil {
		membersMemberList = make([]Member, len(source))
		for i := 0; i < len(source); i++ {
			membersMemberList[i] = c.FromListRandomMembersByRankRow(source[i])
		}
	}
	return membersMemberList
}
func (c *ConverterImpl) FromRsiInfoRow(source dbgen.RsiInfo) *RsiInfo {
	var membersRsiInfo RsiInfo
	membersRsiInfo.Handle = source.Handle
	membersRsiInfo.PrimaryOrg = PgTypeTextToString(source.PrimaryOrg)
	membersRsiInfo.PrimaryOrgSid = PgTypeTextToString(source.PrimaryOrgSid)
	if source.Affiliations != nil {
		membersRsiInfo.Affiliations = make([]string, len(source.Affiliations))
		for i := 0; i < len(source.Affiliations); i++ {
			membersRsiInfo.Affiliations[i] = source.Affiliations[i]
		}
	}
	return &membersRsiInfo
}
func (c *ConverterImpl) FromRsiInfoRows(source []dbgen.RsiInfo) []*RsiInfo {
	var pMembersRsiInfoList []*RsiInfo
	if source != nil {
		pMembersRsiInfoList = make([]*RsiInfo, len(source))
		for i := 0; i < len(source); i++ {
			pMembersRsiInfoList[i] = c.FromRsiInfoRow(source[i])
		}
	}
	return pMembersRsiInfoList
}
func (c *ConverterImpl) pgtypeTimestamptzToPTimeTime(source pgtype.Timestamptz) *time.Time {
	timeTime := PgTypeTimestamptzToTime(source)
	return &timeTime
}
