// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAttendanceIssue = `-- name: AddAttendanceIssue :exec
INSERT INTO attendance_issues (attendance_id, member_id)
VALUES ($1, $2)
ON CONFLICT (attendance_id, member_id) DO NOTHING
`

type AddAttendanceIssueParams struct {
	AttendanceID string `json:"attendance_id"`
	MemberID     string `json:"member_id"`
}

func (q *Queries) AddAttendanceIssue(ctx context.Context, arg AddAttendanceIssueParams) error {
	_, err := q.db.Exec(ctx, addAttendanceIssue, arg.AttendanceID, arg.MemberID)
	return err
}

const addAttendanceMember = `-- name: AddAttendanceMember :exec
INSERT INTO attendance_members (attendance_id, member_id)
VALUES ($1, $2)
ON CONFLICT (attendance_id, member_id) DO NOTHING
`

type AddAttendanceMemberParams struct {
	AttendanceID string `json:"attendance_id"`
	MemberID     string `json:"member_id"`
}

func (q *Queries) AddAttendanceMember(ctx context.Context, arg AddAttendanceMemberParams) error {
	_, err := q.db.Exec(ctx, addAttendanceMember, arg.AttendanceID, arg.MemberID)
	return err
}

const countRecordedMemberAttendanceAfterJoin = `-- name: CountRecordedMemberAttendanceAfterJoin :one
SELECT COUNT(*)::int AS count
FROM attendance a
INNER JOIN attendance_members am ON am.attendance_id = a.id
INNER JOIN members m ON m.id = am.member_id
WHERE am.member_id = $1
  AND a.recorded = TRUE
  AND a.date_created > m.joined
`

func (q *Queries) CountRecordedMemberAttendanceAfterJoin(ctx context.Context, memberID string) (int32, error) {
	row := q.db.QueryRow(ctx, countRecordedMemberAttendanceAfterJoin, memberID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countUniqueAttendanceMembersSince = `-- name: CountUniqueAttendanceMembersSince :one
SELECT COUNT(DISTINCT am.member_id)::int AS count
FROM attendance a
INNER JOIN attendance_members am ON am.attendance_id = a.id
WHERE a.date_created >= $1
`

func (q *Queries) CountUniqueAttendanceMembersSince(ctx context.Context, since pgtype.Timestamptz) (int32, error) {
	row := q.db.QueryRow(ctx, countUniqueAttendanceMembersSince, since)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const deleteAttendance = `-- name: DeleteAttendance :exec
DELETE FROM attendance
WHERE id = $1
`

func (q *Queries) DeleteAttendance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAttendance, id)
	return err
}

const getAttendanceByID = `-- name: GetAttendanceByID :one
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, payouts_total, payouts_per_member, payouts_org_take, from_start, stayed, channel_id, message_id, date_created, date_updated
FROM attendance
WHERE id = $1
`

func (q *Queries) GetAttendanceByID(ctx context.Context, id string) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendanceByID, id)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SubmittedBy,
		&i.Recorded,
		&i.Successful,
		&i.Active,
		&i.Tokenable,
		&i.Status,
		&i.PayoutsTotal,
		&i.PayoutsPerMember,
		&i.PayoutsOrgTake,
		&i.FromStart,
		&i.Stayed,
		&i.ChannelID,
		&i.MessageID,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const listActiveAttendance = `-- name: ListActiveAttendance :many
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, payouts_total, payouts_per_member, payouts_org_take, from_start, stayed, channel_id, message_id, date_created, date_updated
FROM attendance
WHERE recorded = FALSE
   OR status = 'active'
   OR status = 'reverted'
ORDER BY date_created DESC
LIMIT $1::int
`

func (q *Queries) ListActiveAttendance(ctx context.Context, limitRows int32) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listActiveAttendance, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubmittedBy,
			&i.Recorded,
			&i.Successful,
			&i.Active,
			&i.Tokenable,
			&i.Status,
			&i.PayoutsTotal,
			&i.PayoutsPerMember,
			&i.PayoutsOrgTake,
			&i.FromStart,
			&i.Stayed,
			&i.ChannelID,
			&i.MessageID,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAttendance = `-- name: ListAllAttendance :many
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, payouts_total, payouts_per_member, payouts_org_take, from_start, stayed, channel_id, message_id, date_created, date_updated
FROM attendance
ORDER BY date_created DESC
`

func (q *Queries) ListAllAttendance(ctx context.Context) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listAllAttendance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubmittedBy,
			&i.Recorded,
			&i.Successful,
			&i.Active,
			&i.Tokenable,
			&i.Status,
			&i.PayoutsTotal,
			&i.PayoutsPerMember,
			&i.PayoutsOrgTake,
			&i.FromStart,
			&i.Stayed,
			&i.ChannelID,
			&i.MessageID,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceIssueIDs = `-- name: ListAttendanceIssueIDs :many
SELECT member_id
FROM attendance_issues
WHERE attendance_id = $1
ORDER BY member_id
`

func (q *Queries) ListAttendanceIssueIDs(ctx context.Context, attendanceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttendanceIssueIDs, attendanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var member_id string
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceMemberIDs = `-- name: ListAttendanceMemberIDs :many
SELECT member_id
FROM attendance_members
WHERE attendance_id = $1
ORDER BY member_id
`

func (q *Queries) ListAttendanceMemberIDs(ctx context.Context, attendanceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttendanceMemberIDs, attendanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var member_id string
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendancePage = `-- name: ListAttendancePage :many
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, payouts_total, payouts_per_member, payouts_org_take, from_start, stayed, channel_id, message_id, date_created, date_updated
FROM attendance
ORDER BY date_created DESC
OFFSET $1::int
LIMIT $2::int
`

type ListAttendancePageParams struct {
	OffsetRows int32 `json:"offset_rows"`
	LimitRows  int32 `json:"limit_rows"`
}

func (q *Queries) ListAttendancePage(ctx context.Context, arg ListAttendancePageParams) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listAttendancePage, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubmittedBy,
			&i.Recorded,
			&i.Successful,
			&i.Active,
			&i.Tokenable,
			&i.Status,
			&i.PayoutsTotal,
			&i.PayoutsPerMember,
			&i.PayoutsOrgTake,
			&i.FromStart,
			&i.Stayed,
			&i.ChannelID,
			&i.MessageID,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordedAttendance = `-- name: ListRecordedAttendance :many
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, payouts_total, payouts_per_member, payouts_org_take, from_start, stayed, channel_id, message_id, date_created, date_updated
FROM attendance
WHERE recorded = FALSE
   OR status = 'recorded'
ORDER BY date_created DESC
LIMIT $1::int
`

func (q *Queries) ListRecordedAttendance(ctx context.Context, limitRows int32) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listRecordedAttendance, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubmittedBy,
			&i.Recorded,
			&i.Successful,
			&i.Active,
			&i.Tokenable,
			&i.Status,
			&i.PayoutsTotal,
			&i.PayoutsPerMember,
			&i.PayoutsOrgTake,
			&i.FromStart,
			&i.Stayed,
			&i.ChannelID,
			&i.MessageID,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceAttendanceIssues = `-- name: ReplaceAttendanceIssues :exec
DELETE FROM attendance_issues
WHERE attendance_id = $1
`

func (q *Queries) ReplaceAttendanceIssues(ctx context.Context, attendanceID string) error {
	_, err := q.db.Exec(ctx, replaceAttendanceIssues, attendanceID)
	return err
}

const replaceAttendanceMembers = `-- name: ReplaceAttendanceMembers :exec
DELETE FROM attendance_members
WHERE attendance_id = $1
`

func (q *Queries) ReplaceAttendanceMembers(ctx context.Context, attendanceID string) error {
	_, err := q.db.Exec(ctx, replaceAttendanceMembers, attendanceID)
	return err
}

const upsertAttendance = `-- name: UpsertAttendance :exec
INSERT INTO attendance (
    id,
    name,
    submitted_by,
    recorded,
    successful,
    active,
    tokenable,
    status,
    payouts_total,
    payouts_per_member,
    payouts_org_take,
    from_start,
    stayed,
    channel_id,
    message_id,
    date_created,
    date_updated
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    submitted_by = EXCLUDED.submitted_by,
    recorded = EXCLUDED.recorded,
    successful = EXCLUDED.successful,
    active = EXCLUDED.active,
    tokenable = EXCLUDED.tokenable,
    status = EXCLUDED.status,
    payouts_total = EXCLUDED.payouts_total,
    payouts_per_member = EXCLUDED.payouts_per_member,
    payouts_org_take = EXCLUDED.payouts_org_take,
    from_start = EXCLUDED.from_start,
    stayed = EXCLUDED.stayed,
    channel_id = EXCLUDED.channel_id,
    message_id = EXCLUDED.message_id,
    date_created = EXCLUDED.date_created,
    date_updated = EXCLUDED.date_updated
`

type UpsertAttendanceParams struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	SubmittedBy      pgtype.Text        `json:"submitted_by"`
	Recorded         bool               `json:"recorded"`
	Successful       bool               `json:"successful"`
	Active           bool               `json:"active"`
	Tokenable        bool               `json:"tokenable"`
	Status           string             `json:"status"`
	PayoutsTotal     pgtype.Int8        `json:"payouts_total"`
	PayoutsPerMember pgtype.Int8        `json:"payouts_per_member"`
	PayoutsOrgTake   pgtype.Int8        `json:"payouts_org_take"`
	FromStart        []string           `json:"from_start"`
	Stayed           []string           `json:"stayed"`
	ChannelID        string             `json:"channel_id"`
	MessageID        string             `json:"message_id"`
	DateCreated      pgtype.Timestamptz `json:"date_created"`
	DateUpdated      pgtype.Timestamptz `json:"date_updated"`
}

func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) error {
	_, err := q.db.Exec(ctx, upsertAttendance,
		arg.ID,
		arg.Name,
		arg.SubmittedBy,
		arg.Recorded,
		arg.Successful,
		arg.Active,
		arg.Tokenable,
		arg.Status,
		arg.PayoutsTotal,
		arg.PayoutsPerMember,
		arg.PayoutsOrgTake,
		arg.FromStart,
		arg.Stayed,
		arg.ChannelID,
		arg.MessageID,
		arg.DateCreated,
		arg.DateUpdated,
	)
	return err
}
