// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecordedMemberAttendanceAfterJoin = `-- name: CountRecordedMemberAttendanceAfterJoin :one
SELECT COUNT(*)::int AS count
FROM attendance a
INNER JOIN attendance_participants ap ON ap.attendance_id = a.id
INNER JOIN members m ON m.id = ap.member_id
WHERE ap.member_id = $1
  AND a.recorded = TRUE
  AND a.date_created > m.joined
`

func (q *Queries) CountRecordedMemberAttendanceAfterJoin(ctx context.Context, memberID string) (int32, error) {
	row := q.db.QueryRow(ctx, countRecordedMemberAttendanceAfterJoin, memberID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countUniqueAttendanceMembersSince = `-- name: CountUniqueAttendanceMembersSince :one
SELECT COUNT(DISTINCT ap.member_id)::int AS count
FROM attendance a
INNER JOIN attendance_participants ap ON ap.attendance_id = a.id
WHERE a.date_created >= $1
`

func (q *Queries) CountUniqueAttendanceMembersSince(ctx context.Context, since pgtype.Timestamptz) (int32, error) {
	row := q.db.QueryRow(ctx, countUniqueAttendanceMembersSince, since)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const deleteAttendance = `-- name: DeleteAttendance :exec
DELETE FROM attendance
WHERE id = $1
`

func (q *Queries) DeleteAttendance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAttendance, id)
	return err
}

const deleteAttendancePayout = `-- name: DeleteAttendancePayout :exec
DELETE FROM attendance_payouts
WHERE attendance_id = $1
`

func (q *Queries) DeleteAttendancePayout(ctx context.Context, attendanceID string) error {
	_, err := q.db.Exec(ctx, deleteAttendancePayout, attendanceID)
	return err
}

const getAttendanceByID = `-- name: GetAttendanceByID :one
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, channel_id, message_id, date_created, date_updated
FROM attendance
WHERE id = $1
`

func (q *Queries) GetAttendanceByID(ctx context.Context, id string) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendanceByID, id)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SubmittedBy,
		&i.Recorded,
		&i.Successful,
		&i.Active,
		&i.Tokenable,
		&i.Status,
		&i.ChannelID,
		&i.MessageID,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const getAttendancePayout = `-- name: GetAttendancePayout :one
SELECT attendance_id, total, per_member, org_take, date_updated
FROM attendance_payouts
WHERE attendance_id = $1
`

func (q *Queries) GetAttendancePayout(ctx context.Context, attendanceID string) (AttendancePayout, error) {
	row := q.db.QueryRow(ctx, getAttendancePayout, attendanceID)
	var i AttendancePayout
	err := row.Scan(
		&i.AttendanceID,
		&i.Total,
		&i.PerMember,
		&i.OrgTake,
		&i.DateUpdated,
	)
	return i, err
}

const listActiveAttendance = `-- name: ListActiveAttendance :many
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, channel_id, message_id, date_created, date_updated
FROM attendance
WHERE recorded = FALSE
   OR status = 'active'
   OR status = 'reverted'
ORDER BY date_created DESC
LIMIT $1::int
`

func (q *Queries) ListActiveAttendance(ctx context.Context, limitRows int32) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listActiveAttendance, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubmittedBy,
			&i.Recorded,
			&i.Successful,
			&i.Active,
			&i.Tokenable,
			&i.Status,
			&i.ChannelID,
			&i.MessageID,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAttendance = `-- name: ListAllAttendance :many
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, channel_id, message_id, date_created, date_updated
FROM attendance
ORDER BY date_created DESC
`

func (q *Queries) ListAllAttendance(ctx context.Context) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listAllAttendance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubmittedBy,
			&i.Recorded,
			&i.Successful,
			&i.Active,
			&i.Tokenable,
			&i.Status,
			&i.ChannelID,
			&i.MessageID,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendancePage = `-- name: ListAttendancePage :many
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, channel_id, message_id, date_created, date_updated
FROM attendance
ORDER BY date_created DESC
OFFSET $1::int
LIMIT $2::int
`

type ListAttendancePageParams struct {
	OffsetRows int32 `json:"offset_rows"`
	LimitRows  int32 `json:"limit_rows"`
}

func (q *Queries) ListAttendancePage(ctx context.Context, arg ListAttendancePageParams) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listAttendancePage, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubmittedBy,
			&i.Recorded,
			&i.Successful,
			&i.Active,
			&i.Tokenable,
			&i.Status,
			&i.ChannelID,
			&i.MessageID,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceParticipants = `-- name: ListAttendanceParticipants :many
SELECT attendance_id, member_id, joined_at_start, stayed_until_end, has_issue, created_at, updated_at
FROM attendance_participants
WHERE attendance_id = $1
ORDER BY member_id
`

func (q *Queries) ListAttendanceParticipants(ctx context.Context, attendanceID string) ([]AttendanceParticipant, error) {
	rows, err := q.db.Query(ctx, listAttendanceParticipants, attendanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceParticipant
	for rows.Next() {
		var i AttendanceParticipant
		if err := rows.Scan(
			&i.AttendanceID,
			&i.MemberID,
			&i.JoinedAtStart,
			&i.StayedUntilEnd,
			&i.HasIssue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordedAttendance = `-- name: ListRecordedAttendance :many
SELECT id, name, submitted_by, recorded, successful, active, tokenable, status, channel_id, message_id, date_created, date_updated
FROM attendance
WHERE recorded = FALSE
   OR status = 'recorded'
ORDER BY date_created DESC
LIMIT $1::int
`

func (q *Queries) ListRecordedAttendance(ctx context.Context, limitRows int32) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listRecordedAttendance, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubmittedBy,
			&i.Recorded,
			&i.Successful,
			&i.Active,
			&i.Tokenable,
			&i.Status,
			&i.ChannelID,
			&i.MessageID,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceAttendanceParticipants = `-- name: ReplaceAttendanceParticipants :exec
DELETE FROM attendance_participants
WHERE attendance_id = $1
`

func (q *Queries) ReplaceAttendanceParticipants(ctx context.Context, attendanceID string) error {
	_, err := q.db.Exec(ctx, replaceAttendanceParticipants, attendanceID)
	return err
}

const upsertAttendance = `-- name: UpsertAttendance :exec
INSERT INTO attendance (
    id,
    name,
    submitted_by,
    recorded,
    successful,
    active,
    tokenable,
    status,
    channel_id,
    message_id,
    date_created,
    date_updated
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    submitted_by = EXCLUDED.submitted_by,
    recorded = EXCLUDED.recorded,
    successful = EXCLUDED.successful,
    active = EXCLUDED.active,
    tokenable = EXCLUDED.tokenable,
    status = EXCLUDED.status,
    channel_id = EXCLUDED.channel_id,
    message_id = EXCLUDED.message_id,
    date_created = EXCLUDED.date_created,
    date_updated = EXCLUDED.date_updated
`

type UpsertAttendanceParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	SubmittedBy pgtype.Text        `json:"submitted_by"`
	Recorded    bool               `json:"recorded"`
	Successful  bool               `json:"successful"`
	Active      bool               `json:"active"`
	Tokenable   bool               `json:"tokenable"`
	Status      string             `json:"status"`
	ChannelID   string             `json:"channel_id"`
	MessageID   string             `json:"message_id"`
	DateCreated pgtype.Timestamptz `json:"date_created"`
	DateUpdated pgtype.Timestamptz `json:"date_updated"`
}

func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) error {
	_, err := q.db.Exec(ctx, upsertAttendance,
		arg.ID,
		arg.Name,
		arg.SubmittedBy,
		arg.Recorded,
		arg.Successful,
		arg.Active,
		arg.Tokenable,
		arg.Status,
		arg.ChannelID,
		arg.MessageID,
		arg.DateCreated,
		arg.DateUpdated,
	)
	return err
}

const upsertAttendanceParticipant = `-- name: UpsertAttendanceParticipant :exec
INSERT INTO attendance_participants (
    attendance_id,
    member_id,
    joined_at_start,
    stayed_until_end,
    has_issue,
    updated_at
	)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
	)
ON CONFLICT (attendance_id, member_id) DO NOTHING
`

type UpsertAttendanceParticipantParams struct {
	AttendanceID   string             `json:"attendance_id"`
	MemberID       string             `json:"member_id"`
	JoinedAtStart  bool               `json:"joined_at_start"`
	StayedUntilEnd bool               `json:"stayed_until_end"`
	HasIssue       bool               `json:"has_issue"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAttendanceParticipant(ctx context.Context, arg UpsertAttendanceParticipantParams) error {
	_, err := q.db.Exec(ctx, upsertAttendanceParticipant,
		arg.AttendanceID,
		arg.MemberID,
		arg.JoinedAtStart,
		arg.StayedUntilEnd,
		arg.HasIssue,
		arg.UpdatedAt,
	)
	return err
}

const upsertAttendancePayout = `-- name: UpsertAttendancePayout :exec
INSERT INTO attendance_payouts (
    attendance_id,
    total,
    per_member,
    org_take,
    date_updated
	)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
	)
ON CONFLICT (attendance_id) DO UPDATE
SET total = EXCLUDED.total,
    per_member = EXCLUDED.per_member,
    org_take = EXCLUDED.org_take,
    date_updated = EXCLUDED.date_updated
`

type UpsertAttendancePayoutParams struct {
	AttendanceID string             `json:"attendance_id"`
	Total        int64              `json:"total"`
	PerMember    int64              `json:"per_member"`
	OrgTake      int64              `json:"org_take"`
	DateUpdated  pgtype.Timestamptz `json:"date_updated"`
}

func (q *Queries) UpsertAttendancePayout(ctx context.Context, arg UpsertAttendancePayoutParams) error {
	_, err := q.db.Exec(ctx, upsertAttendancePayout,
		arg.AttendanceID,
		arg.Total,
		arg.PerMember,
		arg.OrgTake,
		arg.DateUpdated,
	)
	return err
}
