// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWeeklyCommandCounts = `-- name: GetWeeklyCommandCounts :many
SELECT name,
       COUNT(*)::bigint AS count
FROM command_logs
WHERE occurred_at >= NOW() - INTERVAL '7 days'
GROUP BY name
ORDER BY count DESC, name ASC
`

type GetWeeklyCommandCountsRow struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) GetWeeklyCommandCounts(ctx context.Context) ([]GetWeeklyCommandCountsRow, error) {
	rows, err := q.db.Query(ctx, getWeeklyCommandCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeeklyCommandCountsRow
	for rows.Next() {
		var i GetWeeklyCommandCountsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCommandLog = `-- name: InsertCommandLog :exec
INSERT INTO command_logs (
    name,
    occurred_at,
    user_id,
    interaction_type,
    button_id,
    error_text,
    options_json
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type InsertCommandLogParams struct {
	Name            string             `json:"name"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	UserID          string             `json:"user_id"`
	InteractionType int32              `json:"interaction_type"`
	ButtonID        string             `json:"button_id"`
	ErrorText       string             `json:"error_text"`
	OptionsJson     string             `json:"options_json"`
}

func (q *Queries) InsertCommandLog(ctx context.Context, arg InsertCommandLogParams) error {
	_, err := q.db.Exec(ctx, insertCommandLog,
		arg.Name,
		arg.OccurredAt,
		arg.UserID,
		arg.InteractionType,
		arg.ButtonID,
		arg.ErrorText,
		arg.OptionsJson,
	)
	return err
}
