// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configs.sql

package dbgen

import (
	"context"
)

const deleteAllAttendanceNames = `-- name: DeleteAllAttendanceNames :exec
DELETE FROM attendance_names
`

func (q *Queries) DeleteAllAttendanceNames(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAttendanceNames)
	return err
}

const deleteAllAttendanceTags = `-- name: DeleteAllAttendanceTags :exec
DELETE FROM attendance_tags
`

func (q *Queries) DeleteAllAttendanceTags(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAttendanceTags)
	return err
}

const deleteAttendanceName = `-- name: DeleteAttendanceName :exec
DELETE FROM attendance_names
WHERE name = $1
`

func (q *Queries) DeleteAttendanceName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteAttendanceName, name)
	return err
}

const deleteAttendanceTag = `-- name: DeleteAttendanceTag :exec
DELETE FROM attendance_tags
WHERE tag = $1
`

func (q *Queries) DeleteAttendanceTag(ctx context.Context, tag string) error {
	_, err := q.db.Exec(ctx, deleteAttendanceTag, tag)
	return err
}

const insertAttendanceName = `-- name: InsertAttendanceName :exec
INSERT INTO attendance_names (name)
VALUES ($1)
ON CONFLICT (name) DO NOTHING
`

func (q *Queries) InsertAttendanceName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertAttendanceName, name)
	return err
}

const insertAttendanceTag = `-- name: InsertAttendanceTag :exec
INSERT INTO attendance_tags (tag)
VALUES ($1)
ON CONFLICT (tag) DO NOTHING
`

func (q *Queries) InsertAttendanceTag(ctx context.Context, tag string) error {
	_, err := q.db.Exec(ctx, insertAttendanceTag, tag)
	return err
}

const listAttendanceNames = `-- name: ListAttendanceNames :many
SELECT name
FROM attendance_names
ORDER BY name
`

func (q *Queries) ListAttendanceNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttendanceNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceTags = `-- name: ListAttendanceTags :many
SELECT tag
FROM attendance_tags
ORDER BY tag
`

func (q *Queries) ListAttendanceTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttendanceTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
