// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legacy_docs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertBlueprintDoc = `-- name: UpsertBlueprintDoc :exec
INSERT INTO blueprint_docs (id, payload_json, updated_at)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (id) DO UPDATE
SET payload_json = EXCLUDED.payload_json,
    updated_at = EXCLUDED.updated_at
`

type UpsertBlueprintDocParams struct {
	ID          string             `json:"id"`
	PayloadJson string             `json:"payload_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertBlueprintDoc(ctx context.Context, arg UpsertBlueprintDocParams) error {
	_, err := q.db.Exec(ctx, upsertBlueprintDoc, arg.ID, arg.PayloadJson, arg.UpdatedAt)
	return err
}

const upsertKanbanCard = `-- name: UpsertKanbanCard :exec
INSERT INTO kanban_cards (id, payload_json, updated_at)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (id) DO UPDATE
SET payload_json = EXCLUDED.payload_json,
    updated_at = EXCLUDED.updated_at
`

type UpsertKanbanCardParams struct {
	ID          string             `json:"id"`
	PayloadJson string             `json:"payload_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertKanbanCard(ctx context.Context, arg UpsertKanbanCardParams) error {
	_, err := q.db.Exec(ctx, upsertKanbanCard, arg.ID, arg.PayloadJson, arg.UpdatedAt)
	return err
}

const upsertSOSTicket = `-- name: UpsertSOSTicket :exec
INSERT INTO sos_tickets (id, member_id, payload_json, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (id) DO UPDATE
SET member_id = EXCLUDED.member_id,
    payload_json = EXCLUDED.payload_json,
    updated_at = EXCLUDED.updated_at
`

type UpsertSOSTicketParams struct {
	ID          string             `json:"id"`
	MemberID    string             `json:"member_id"`
	PayloadJson string             `json:"payload_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSOSTicket(ctx context.Context, arg UpsertSOSTicketParams) error {
	_, err := q.db.Exec(ctx, upsertSOSTicket,
		arg.ID,
		arg.MemberID,
		arg.PayloadJson,
		arg.UpdatedAt,
	)
	return err
}
