// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMemberBlueprint = `-- name: AddMemberBlueprint :exec
INSERT INTO member_blueprints (member_id, blueprint_id)
VALUES ($1, $2)
ON CONFLICT (member_id, blueprint_id) DO NOTHING
`

type AddMemberBlueprintParams struct {
	MemberID    string `json:"member_id"`
	BlueprintID string `json:"blueprint_id"`
}

func (q *Queries) AddMemberBlueprint(ctx context.Context, arg AddMemberBlueprintParams) error {
	_, err := q.db.Exec(ctx, addMemberBlueprint, arg.MemberID, arg.BlueprintID)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
UPDATE members
SET date_left = COALESCE($1, NOW()),
    reason_left = $2
WHERE id = $3
`

type DeleteMemberParams struct {
	DateLeft   pgtype.Timestamptz `json:"date_left"`
	ReasonLeft pgtype.Text        `json:"reason_left"`
	ID         string             `json:"id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.DateLeft, arg.ReasonLeft, arg.ID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT 
  m.id, m.name, m.rank, m.joined, m.updated, m.is_bot, m.is_ally, m.is_affiliate, m.is_guest, m.on_rsi, m.dm_opt_out, m.date_left, m.reason_left,
  ri.primary_org,
  ri.affiliations
FROM members m
LEFT JOIN rsi_info ri ON ri.handle = m.name
WHERE id = $1
`

type GetMemberRow struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Rank         int32              `json:"rank"`
	Joined       pgtype.Timestamptz `json:"joined"`
	Updated      pgtype.Timestamptz `json:"updated"`
	IsBot        bool               `json:"is_bot"`
	IsAlly       bool               `json:"is_ally"`
	IsAffiliate  bool               `json:"is_affiliate"`
	IsGuest      bool               `json:"is_guest"`
	OnRsi        bool               `json:"on_rsi"`
	DmOptOut     bool               `json:"dm_opt_out"`
	DateLeft     pgtype.Timestamptz `json:"date_left"`
	ReasonLeft   pgtype.Text        `json:"reason_left"`
	PrimaryOrg   pgtype.Text        `json:"primary_org"`
	Affiliations []string           `json:"affiliations"`
}

func (q *Queries) GetMember(ctx context.Context, id string) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rank,
		&i.Joined,
		&i.Updated,
		&i.IsBot,
		&i.IsAlly,
		&i.IsAffiliate,
		&i.IsGuest,
		&i.OnRsi,
		&i.DmOptOut,
		&i.DateLeft,
		&i.ReasonLeft,
		&i.PrimaryOrg,
		&i.Affiliations,
	)
	return i, err
}

const getMemberIDs = `-- name: GetMemberIDs :many
SELECT id
FROM members
ORDER BY id
`

func (q *Queries) GetMemberIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getMemberIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByBlueprint = `-- name: ListMembersByBlueprint :many
SELECT 
  m.id, m.name, m.rank, m.joined, m.updated, m.is_bot, m.is_ally, m.is_affiliate, m.is_guest, m.on_rsi, m.dm_opt_out, m.date_left, m.reason_left,
  ri.primary_org,
  ri.affiliations
FROM members m
LEFT JOIN rsi_info ri ON ri.handle = m.name
INNER JOIN member_blueprints mb ON mb.member_id = m.id
WHERE mb.blueprint_id = $1
ORDER BY m.id
`

type ListMembersByBlueprintRow struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Rank         int32              `json:"rank"`
	Joined       pgtype.Timestamptz `json:"joined"`
	Updated      pgtype.Timestamptz `json:"updated"`
	IsBot        bool               `json:"is_bot"`
	IsAlly       bool               `json:"is_ally"`
	IsAffiliate  bool               `json:"is_affiliate"`
	IsGuest      bool               `json:"is_guest"`
	OnRsi        bool               `json:"on_rsi"`
	DmOptOut     bool               `json:"dm_opt_out"`
	DateLeft     pgtype.Timestamptz `json:"date_left"`
	ReasonLeft   pgtype.Text        `json:"reason_left"`
	PrimaryOrg   pgtype.Text        `json:"primary_org"`
	Affiliations []string           `json:"affiliations"`
}

func (q *Queries) ListMembersByBlueprint(ctx context.Context, blueprintID string) ([]ListMembersByBlueprintRow, error) {
	rows, err := q.db.Query(ctx, listMembersByBlueprint, blueprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByBlueprintRow
	for rows.Next() {
		var i ListMembersByBlueprintRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.Joined,
			&i.Updated,
			&i.IsBot,
			&i.IsAlly,
			&i.IsAffiliate,
			&i.IsGuest,
			&i.OnRsi,
			&i.DmOptOut,
			&i.DateLeft,
			&i.ReasonLeft,
			&i.PrimaryOrg,
			&i.Affiliations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByIDs = `-- name: ListMembersByIDs :many
SELECT 
  m.id, m.name, m.rank, m.joined, m.updated, m.is_bot, m.is_ally, m.is_affiliate, m.is_guest, m.on_rsi, m.dm_opt_out, m.date_left, m.reason_left,
  ri.primary_org,
  ri.affiliations
FROM members m
LEFT JOIN rsi_info ri ON ri.handle = m.name
WHERE id = ANY($1::text[])
`

type ListMembersByIDsRow struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Rank         int32              `json:"rank"`
	Joined       pgtype.Timestamptz `json:"joined"`
	Updated      pgtype.Timestamptz `json:"updated"`
	IsBot        bool               `json:"is_bot"`
	IsAlly       bool               `json:"is_ally"`
	IsAffiliate  bool               `json:"is_affiliate"`
	IsGuest      bool               `json:"is_guest"`
	OnRsi        bool               `json:"on_rsi"`
	DmOptOut     bool               `json:"dm_opt_out"`
	DateLeft     pgtype.Timestamptz `json:"date_left"`
	ReasonLeft   pgtype.Text        `json:"reason_left"`
	PrimaryOrg   pgtype.Text        `json:"primary_org"`
	Affiliations []string           `json:"affiliations"`
}

func (q *Queries) ListMembersByIDs(ctx context.Context, ids []string) ([]ListMembersByIDsRow, error) {
	rows, err := q.db.Query(ctx, listMembersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByIDsRow
	for rows.Next() {
		var i ListMembersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.Joined,
			&i.Updated,
			&i.IsBot,
			&i.IsAlly,
			&i.IsAffiliate,
			&i.IsGuest,
			&i.OnRsi,
			&i.DmOptOut,
			&i.DateLeft,
			&i.ReasonLeft,
			&i.PrimaryOrg,
			&i.Affiliations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersPage = `-- name: ListMembersPage :many
SELECT 
  m.id, m.name, m.rank, m.joined, m.updated, m.is_bot, m.is_ally, m.is_affiliate, m.is_guest, m.on_rsi, m.dm_opt_out, m.date_left, m.reason_left,
  ri.primary_org,
  ri.affiliations
FROM members m
LEFT JOIN rsi_info ri ON ri.handle = m.name
WHERE (NOT $1::boolean OR is_bot = FALSE)
ORDER BY id
OFFSET $2::int
LIMIT $3::int
`

type ListMembersPageParams struct {
	ExcludeBots bool  `json:"exclude_bots"`
	OffsetRows  int32 `json:"offset_rows"`
	LimitRows   int32 `json:"limit_rows"`
}

type ListMembersPageRow struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Rank         int32              `json:"rank"`
	Joined       pgtype.Timestamptz `json:"joined"`
	Updated      pgtype.Timestamptz `json:"updated"`
	IsBot        bool               `json:"is_bot"`
	IsAlly       bool               `json:"is_ally"`
	IsAffiliate  bool               `json:"is_affiliate"`
	IsGuest      bool               `json:"is_guest"`
	OnRsi        bool               `json:"on_rsi"`
	DmOptOut     bool               `json:"dm_opt_out"`
	DateLeft     pgtype.Timestamptz `json:"date_left"`
	ReasonLeft   pgtype.Text        `json:"reason_left"`
	PrimaryOrg   pgtype.Text        `json:"primary_org"`
	Affiliations []string           `json:"affiliations"`
}

func (q *Queries) ListMembersPage(ctx context.Context, arg ListMembersPageParams) ([]ListMembersPageRow, error) {
	rows, err := q.db.Query(ctx, listMembersPage, arg.ExcludeBots, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersPageRow
	for rows.Next() {
		var i ListMembersPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.Joined,
			&i.Updated,
			&i.IsBot,
			&i.IsAlly,
			&i.IsAffiliate,
			&i.IsGuest,
			&i.OnRsi,
			&i.DmOptOut,
			&i.DateLeft,
			&i.ReasonLeft,
			&i.PrimaryOrg,
			&i.Affiliations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotions = `-- name: ListPromotions :many
WITH attendance_counts AS (
  SELECT
    ap.member_id,
    COUNT(*)::int AS attendance_count
  FROM attendance_participants ap
  JOIN attendance a ON a.id = ap.attendance_id
  JOIN members m2 ON m2.id = ap.member_id
  WHERE a.recorded = TRUE
    AND a.date_created > m2.joined
  GROUP BY ap.member_id
)
SELECT
  m.id,
  m.name,
  m.rank AS current_rank,
  COALESCE(ac.attendance_count, 0) AS attendance_count,
  CASE
    WHEN m.rank = 7 AND COALESCE(ac.attendance_count, 0) >= 3 THEN 6
    WHEN m.rank = 6 AND COALESCE(ac.attendance_count, 0) >= 10 THEN 5
    WHEN m.rank = 5 AND COALESCE(ac.attendance_count, 0) >= 20 THEN 4
    ELSE NULL
  END::int AS next_rank
FROM members m
LEFT JOIN attendance_counts ac ON ac.member_id = m.id
LEFT JOIN rsi_info ri ON ri.handle = m.name
WHERE m.rank <= 7
  AND m.is_ally = FALSE
  AND m.is_affiliate = FALSE
  AND (
    (m.rank = 7 AND COALESCE(ac.attendance_count, 0) >= 3) OR
    (m.rank = 6 AND COALESCE(ac.attendance_count, 0) >= 10) OR
    (m.rank = 5 AND COALESCE(ac.attendance_count, 0) >= 20)
  )
  AND ri.primary_org = 'SOLARMADA'
ORDER BY attendance_count DESC, m.id
`

type ListPromotionsRow struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	CurrentRank     int32  `json:"current_rank"`
	AttendanceCount int32  `json:"attendance_count"`
	NextRank        int32  `json:"next_rank"`
}

func (q *Queries) ListPromotions(ctx context.Context) ([]ListPromotionsRow, error) {
	rows, err := q.db.Query(ctx, listPromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromotionsRow
	for rows.Next() {
		var i ListPromotionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CurrentRank,
			&i.AttendanceCount,
			&i.NextRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRandomMembersByRank = `-- name: ListRandomMembersByRank :many
SELECT 
  m.id, m.name, m.rank, m.joined, m.updated, m.is_bot, m.is_ally, m.is_affiliate, m.is_guest, m.on_rsi, m.dm_opt_out, m.date_left, m.reason_left,
  ri.primary_org,
  ri.affiliations
FROM members m
LEFT JOIN rsi_info ri ON ri.handle = m.name
WHERE rank <= $1::int
  AND rank <> 0
ORDER BY random()
LIMIT $2::int
`

type ListRandomMembersByRankParams struct {
	MaxRank   int32 `json:"max_rank"`
	LimitRows int32 `json:"limit_rows"`
}

type ListRandomMembersByRankRow struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Rank         int32              `json:"rank"`
	Joined       pgtype.Timestamptz `json:"joined"`
	Updated      pgtype.Timestamptz `json:"updated"`
	IsBot        bool               `json:"is_bot"`
	IsAlly       bool               `json:"is_ally"`
	IsAffiliate  bool               `json:"is_affiliate"`
	IsGuest      bool               `json:"is_guest"`
	OnRsi        bool               `json:"on_rsi"`
	DmOptOut     bool               `json:"dm_opt_out"`
	DateLeft     pgtype.Timestamptz `json:"date_left"`
	ReasonLeft   pgtype.Text        `json:"reason_left"`
	PrimaryOrg   pgtype.Text        `json:"primary_org"`
	Affiliations []string           `json:"affiliations"`
}

func (q *Queries) ListRandomMembersByRank(ctx context.Context, arg ListRandomMembersByRankParams) ([]ListRandomMembersByRankRow, error) {
	rows, err := q.db.Query(ctx, listRandomMembersByRank, arg.MaxRank, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRandomMembersByRankRow
	for rows.Next() {
		var i ListRandomMembersByRankRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.Joined,
			&i.Updated,
			&i.IsBot,
			&i.IsAlly,
			&i.IsAffiliate,
			&i.IsGuest,
			&i.OnRsi,
			&i.DmOptOut,
			&i.DateLeft,
			&i.ReasonLeft,
			&i.PrimaryOrg,
			&i.Affiliations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceMemberBlueprints = `-- name: ReplaceMemberBlueprints :exec
DELETE FROM member_blueprints
WHERE member_id = $1
`

func (q *Queries) ReplaceMemberBlueprints(ctx context.Context, memberID string) error {
	_, err := q.db.Exec(ctx, replaceMemberBlueprints, memberID)
	return err
}

const upsertMember = `-- name: UpsertMember :exec
INSERT INTO members (
    id,
    name,
    rank,
    joined,
    updated,
    is_bot,
    is_ally,
  is_affiliate,
  dm_opt_out
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, NOW()),
    $6,
    $7,
    $8,
  $9
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    rank = EXCLUDED.rank,
    joined = EXCLUDED.joined,
    updated = EXCLUDED.updated,
    is_bot = EXCLUDED.is_bot,
    is_ally = EXCLUDED.is_ally,
    is_affiliate = EXCLUDED.is_affiliate,
  dm_opt_out = EXCLUDED.dm_opt_out
`

type UpsertMemberParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Rank        int32              `json:"rank"`
	Joined      pgtype.Timestamptz `json:"joined"`
	Updated     interface{}        `json:"updated"`
	IsBot       bool               `json:"is_bot"`
	IsAlly      bool               `json:"is_ally"`
	IsAffiliate bool               `json:"is_affiliate"`
	DmOptOut    bool               `json:"dm_opt_out"`
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) error {
	_, err := q.db.Exec(ctx, upsertMember,
		arg.ID,
		arg.Name,
		arg.Rank,
		arg.Joined,
		arg.Updated,
		arg.IsBot,
		arg.IsAlly,
		arg.IsAffiliate,
		arg.DmOptOut,
	)
	return err
}
