// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMemberBlueprint = `-- name: AddMemberBlueprint :exec
INSERT INTO member_blueprints (member_id, blueprint_id)
VALUES ($1, $2)
ON CONFLICT (member_id, blueprint_id) DO NOTHING
`

type AddMemberBlueprintParams struct {
	MemberID    string `json:"member_id"`
	BlueprintID string `json:"blueprint_id"`
}

func (q *Queries) AddMemberBlueprint(ctx context.Context, arg AddMemberBlueprintParams) error {
	_, err := q.db.Exec(ctx, addMemberBlueprint, arg.MemberID, arg.BlueprintID)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members
WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, name, rank, joined, updated, is_bot, is_ally, is_affiliate, is_guest
FROM members
WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rank,
		&i.Joined,
		&i.Updated,
		&i.IsBot,
		&i.IsAlly,
		&i.IsAffiliate,
		&i.IsGuest,
	)
	return i, err
}

const getMemberIDs = `-- name: GetMemberIDs :many
SELECT id
FROM members
ORDER BY id
`

func (q *Queries) GetMemberIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getMemberIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByBlueprint = `-- name: ListMembersByBlueprint :many
SELECT m.id, m.name, m.rank, m.joined, m.updated, m.is_bot, m.is_ally, m.is_affiliate, m.is_guest
FROM members m
INNER JOIN member_blueprints mb ON mb.member_id = m.id
WHERE mb.blueprint_id = $1
ORDER BY m.id
`

func (q *Queries) ListMembersByBlueprint(ctx context.Context, blueprintID string) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembersByBlueprint, blueprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.Joined,
			&i.Updated,
			&i.IsBot,
			&i.IsAlly,
			&i.IsAffiliate,
			&i.IsGuest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByIDs = `-- name: ListMembersByIDs :many
SELECT id, name, rank, joined, updated, is_bot, is_ally, is_affiliate, is_guest
FROM members
WHERE id = ANY($1::text[])
`

func (q *Queries) ListMembersByIDs(ctx context.Context, ids []string) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.Joined,
			&i.Updated,
			&i.IsBot,
			&i.IsAlly,
			&i.IsAffiliate,
			&i.IsGuest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersPage = `-- name: ListMembersPage :many
SELECT id, name, rank, joined, updated, is_bot, is_ally, is_affiliate, is_guest
FROM members
WHERE (NOT $1::boolean OR is_bot = FALSE)
ORDER BY id
OFFSET $2::int
LIMIT $3::int
`

type ListMembersPageParams struct {
	ExcludeBots bool  `json:"exclude_bots"`
	OffsetRows  int32 `json:"offset_rows"`
	LimitRows   int32 `json:"limit_rows"`
}

func (q *Queries) ListMembersPage(ctx context.Context, arg ListMembersPageParams) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembersPage, arg.ExcludeBots, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.Joined,
			&i.Updated,
			&i.IsBot,
			&i.IsAlly,
			&i.IsAffiliate,
			&i.IsGuest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRandomMembersByRank = `-- name: ListRandomMembersByRank :many
SELECT id, name, rank, joined, updated, is_bot, is_ally, is_affiliate, is_guest
FROM members
WHERE rank <= $1::int
  AND rank <> 0
ORDER BY random()
LIMIT $2::int
`

type ListRandomMembersByRankParams struct {
	MaxRank   int32 `json:"max_rank"`
	LimitRows int32 `json:"limit_rows"`
}

func (q *Queries) ListRandomMembersByRank(ctx context.Context, arg ListRandomMembersByRankParams) ([]Member, error) {
	rows, err := q.db.Query(ctx, listRandomMembersByRank, arg.MaxRank, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.Joined,
			&i.Updated,
			&i.IsBot,
			&i.IsAlly,
			&i.IsAffiliate,
			&i.IsGuest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceMemberBlueprints = `-- name: ReplaceMemberBlueprints :exec
DELETE FROM member_blueprints
WHERE member_id = $1
`

func (q *Queries) ReplaceMemberBlueprints(ctx context.Context, memberID string) error {
	_, err := q.db.Exec(ctx, replaceMemberBlueprints, memberID)
	return err
}

const upsertMember = `-- name: UpsertMember :exec
INSERT INTO members (
    id,
    name,
    rank,
    joined,
    updated,
    is_bot,
    is_ally,
  is_affiliate,
  is_guest
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
  $9
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    rank = EXCLUDED.rank,
    joined = EXCLUDED.joined,
    updated = EXCLUDED.updated,
    is_bot = EXCLUDED.is_bot,
    is_ally = EXCLUDED.is_ally,
    is_affiliate = EXCLUDED.is_affiliate,
  is_guest = EXCLUDED.is_guest
`

type UpsertMemberParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Rank        int32              `json:"rank"`
	Joined      pgtype.Timestamptz `json:"joined"`
	Updated     pgtype.Timestamptz `json:"updated"`
	IsBot       bool               `json:"is_bot"`
	IsAlly      bool               `json:"is_ally"`
	IsAffiliate bool               `json:"is_affiliate"`
	IsGuest     bool               `json:"is_guest"`
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) error {
	_, err := q.db.Exec(ctx, upsertMember,
		arg.ID,
		arg.Name,
		arg.Rank,
		arg.Joined,
		arg.Updated,
		arg.IsBot,
		arg.IsAlly,
		arg.IsAffiliate,
		arg.IsGuest,
	)
	return err
}
