// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID         int64              `json:"id"`
	WhoID      pgtype.Text        `json:"who_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	What       string             `json:"what"`
	WhereText  string             `json:"where_text"`
}

type Attendance struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	SubmittedBy pgtype.Text        `json:"submitted_by"`
	Recorded    bool               `json:"recorded"`
	Successful  bool               `json:"successful"`
	Active      bool               `json:"active"`
	Tokenable   bool               `json:"tokenable"`
	Status      string             `json:"status"`
	ChannelID   string             `json:"channel_id"`
	MessageID   string             `json:"message_id"`
	DateCreated pgtype.Timestamptz `json:"date_created"`
	DateUpdated pgtype.Timestamptz `json:"date_updated"`
}

type AttendanceName struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AttendanceParticipant struct {
	AttendanceID   string             `json:"attendance_id"`
	MemberID       string             `json:"member_id"`
	JoinedAtStart  bool               `json:"joined_at_start"`
	StayedUntilEnd bool               `json:"stayed_until_end"`
	HasIssue       bool               `json:"has_issue"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IsManager      bool               `json:"is_manager"`
}

type AttendancePayout struct {
	AttendanceID string             `json:"attendance_id"`
	Total        int64              `json:"total"`
	PerMember    int64              `json:"per_member"`
	OrgTake      int64              `json:"org_take"`
	DateUpdated  pgtype.Timestamptz `json:"date_updated"`
}

type AttendanceTag struct {
	Tag       string             `json:"tag"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BlueprintDoc struct {
	ID          string             `json:"id"`
	PayloadJson string             `json:"payload_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CommandLog struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	UserID          string             `json:"user_id"`
	InteractionType int32              `json:"interaction_type"`
	ButtonID        string             `json:"button_id"`
	ErrorText       string             `json:"error_text"`
	OptionsJson     string             `json:"options_json"`
}

type Giveaway struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	ItemsJson      string             `json:"items_json"`
	AttendanceID   pgtype.Text        `json:"attendance_id"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Ended          bool               `json:"ended"`
	ChannelID      string             `json:"channel_id"`
	EmbedMessageID string             `json:"embed_message_id"`
	InputMessageID string             `json:"input_message_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type KanbanCard struct {
	ID          string             `json:"id"`
	PayloadJson string             `json:"payload_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Member struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Rank        int32              `json:"rank"`
	Joined      pgtype.Timestamptz `json:"joined"`
	Updated     pgtype.Timestamptz `json:"updated"`
	IsBot       bool               `json:"is_bot"`
	IsAlly      bool               `json:"is_ally"`
	IsAffiliate bool               `json:"is_affiliate"`
	IsGuest     bool               `json:"is_guest"`
	OnRsi       bool               `json:"on_rsi"`
	DmOptOut    bool               `json:"dm_opt_out"`
	DateLeft    pgtype.Timestamptz `json:"date_left"`
	ReasonLeft  pgtype.Text        `json:"reason_left"`
}

type MemberBlueprint struct {
	MemberID    string `json:"member_id"`
	BlueprintID string `json:"blueprint_id"`
}

type Raffle struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	AttendanceID pgtype.Text        `json:"attendance_id"`
	Prize        string             `json:"prize"`
	Quantity     int32              `json:"quantity"`
	TicketsJson  string             `json:"tickets_json"`
	Winners      []string           `json:"winners"`
	Ended        bool               `json:"ended"`
	Test         bool               `json:"test"`
	ChannelID    string             `json:"channel_id"`
	MessageID    string             `json:"message_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RsiInfo struct {
	Handle        string      `json:"handle"`
	PrimaryOrg    pgtype.Text `json:"primary_org"`
	PrimaryOrgSid pgtype.Text `json:"primary_org_sid"`
	Affiliations  []string    `json:"affiliations"`
}

type SchemaMigration struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type SosTicket struct {
	ID          string             `json:"id"`
	MemberID    string             `json:"member_id"`
	PayloadJson string             `json:"payload_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Token struct {
	ID           string             `json:"id"`
	MemberID     string             `json:"member_id"`
	Amount       int32              `json:"amount"`
	Reason       string             `json:"reason"`
	AttendanceID pgtype.Text        `json:"attendance_id"`
	Comment      pgtype.Text        `json:"comment"`
	GiverID      pgtype.Text        `json:"giver_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
