// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attendance struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	SubmittedBy pgtype.Text        `json:"submitted_by"`
	Recorded    bool               `json:"recorded"`
	Successful  bool               `json:"successful"`
	Active      bool               `json:"active"`
	Tokenable   bool               `json:"tokenable"`
	Status      string             `json:"status"`
	ChannelID   string             `json:"channel_id"`
	MessageID   string             `json:"message_id"`
	DateCreated pgtype.Timestamptz `json:"date_created"`
	DateUpdated pgtype.Timestamptz `json:"date_updated"`
}

type AttendanceParticipant struct {
	AttendanceID   string             `json:"attendance_id"`
	MemberID       string             `json:"member_id"`
	JoinedAtStart  bool               `json:"joined_at_start"`
	StayedUntilEnd bool               `json:"stayed_until_end"`
	HasIssue       bool               `json:"has_issue"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AttendancePayout struct {
	AttendanceID string             `json:"attendance_id"`
	Total        int64              `json:"total"`
	PerMember    int64              `json:"per_member"`
	OrgTake      int64              `json:"org_take"`
	DateUpdated  pgtype.Timestamptz `json:"date_updated"`
}

type Member struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Rank        int32              `json:"rank"`
	Joined      pgtype.Timestamptz `json:"joined"`
	Updated     pgtype.Timestamptz `json:"updated"`
	IsBot       bool               `json:"is_bot"`
	IsAlly      bool               `json:"is_ally"`
	IsAffiliate bool               `json:"is_affiliate"`
	IsGuest     bool               `json:"is_guest"`
}

type MemberBlueprint struct {
	MemberID    string `json:"member_id"`
	BlueprintID string `json:"blueprint_id"`
}

type Token struct {
	ID           string             `json:"id"`
	MemberID     string             `json:"member_id"`
	Amount       int32              `json:"amount"`
	Reason       string             `json:"reason"`
	AttendanceID pgtype.Text        `json:"attendance_id"`
	Comment      pgtype.Text        `json:"comment"`
	GiverID      pgtype.Text        `json:"giver_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
