// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteProjectTask = `-- name: DeleteProjectTask :exec
DELETE FROM project_kanban_tasks WHERE id = $1
`

func (q *Queries) DeleteProjectTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProjectTask, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, owner_id, status_id, due_at, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.StatusID,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTaskByID = `-- name: GetProjectTaskByID :one
SELECT id, project_id, status_name, title, description, position, priority, due_at, assignee_id, parent_task_id, created_at, updated_at FROM project_kanban_tasks WHERE id = $1
`

func (q *Queries) GetProjectTaskByID(ctx context.Context, id string) (ProjectKanbanTask, error) {
	row := q.db.QueryRow(ctx, getProjectTaskByID, id)
	var i ProjectKanbanTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StatusName,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueAt,
		&i.AssigneeID,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProjectTaskHistory = `-- name: InsertProjectTaskHistory :one
INSERT INTO project_kanban_task_history (task_id, action, performed_by_id, performed_at, details)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, action, performed_by_id, performed_at, details
`

type InsertProjectTaskHistoryParams struct {
	TaskID        string             `json:"task_id"`
	Action        string             `json:"action"`
	PerformedByID pgtype.Text        `json:"performed_by_id"`
	PerformedAt   pgtype.Timestamptz `json:"performed_at"`
	Details       []byte             `json:"details"`
}

func (q *Queries) InsertProjectTaskHistory(ctx context.Context, arg InsertProjectTaskHistoryParams) (ProjectKanbanTaskHistory, error) {
	row := q.db.QueryRow(ctx, insertProjectTaskHistory,
		arg.TaskID,
		arg.Action,
		arg.PerformedByID,
		arg.PerformedAt,
		arg.Details,
	)
	var i ProjectKanbanTaskHistory
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Action,
		&i.PerformedByID,
		&i.PerformedAt,
		&i.Details,
	)
	return i, err
}

const listProjectStatuses = `-- name: ListProjectStatuses :many
SELECT id, name, created_at, updated_at FROM project_statuses ORDER BY created_at DESC
`

func (q *Queries) ListProjectStatuses(ctx context.Context) ([]ProjectStatus, error) {
	rows, err := q.db.Query(ctx, listProjectStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectStatus
	for rows.Next() {
		var i ProjectStatus
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTaskHistory = `-- name: ListProjectTaskHistory :many
SELECT id, task_id, action, performed_by_id, performed_at, details FROM project_kanban_task_history WHERE task_id = $1 ORDER BY performed_at DESC
`

func (q *Queries) ListProjectTaskHistory(ctx context.Context, taskID string) ([]ProjectKanbanTaskHistory, error) {
	rows, err := q.db.Query(ctx, listProjectTaskHistory, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectKanbanTaskHistory
	for rows.Next() {
		var i ProjectKanbanTaskHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Action,
			&i.PerformedByID,
			&i.PerformedAt,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT id, project_id, status_name, title, description, position, priority, due_at, assignee_id, parent_task_id, created_at, updated_at FROM project_kanban_tasks WHERE project_id = $1 ORDER BY position ASC
`

func (q *Queries) ListProjectTasks(ctx context.Context, projectID string) ([]ProjectKanbanTask, error) {
	rows, err := q.db.Query(ctx, listProjectTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectKanbanTask
	for rows.Next() {
		var i ProjectKanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StatusName,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.Priority,
			&i.DueAt,
			&i.AssigneeID,
			&i.ParentTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasksByAssignee = `-- name: ListProjectTasksByAssignee :many
SELECT id, project_id, status_name, title, description, position, priority, due_at, assignee_id, parent_task_id, created_at, updated_at FROM project_kanban_tasks WHERE assignee_id = $1 ORDER BY position ASC
`

func (q *Queries) ListProjectTasksByAssignee(ctx context.Context, assigneeID pgtype.Text) ([]ProjectKanbanTask, error) {
	rows, err := q.db.Query(ctx, listProjectTasksByAssignee, assigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectKanbanTask
	for rows.Next() {
		var i ProjectKanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StatusName,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.Priority,
			&i.DueAt,
			&i.AssigneeID,
			&i.ParentTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, owner_id, status_id, due_at, created_at, updated_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.StatusID,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (id, name, description, owner_id, status_id, due_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    owner_id = EXCLUDED.owner_id,
    status_id = EXCLUDED.status_id,
    due_at = EXCLUDED.due_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, description, owner_id, status_id, due_at, created_at, updated_at
`

type UpsertProjectParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	OwnerID     pgtype.Text        `json:"owner_id"`
	StatusID    int32              `json:"status_id"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.StatusID,
		arg.DueAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.StatusID,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectStatus = `-- name: UpsertProjectStatus :one
INSERT INTO project_statuses (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, created_at, updated_at
`

type UpsertProjectStatusParams struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertProjectStatus(ctx context.Context, arg UpsertProjectStatusParams) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, upsertProjectStatus,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectTask = `-- name: UpsertProjectTask :one
INSERT INTO project_kanban_tasks (id, project_id, status_name, title, description, position, priority, due_at, assignee_id, parent_task_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    status_name = EXCLUDED.status_name,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    position = EXCLUDED.position,
    priority = EXCLUDED.priority,
    due_at = EXCLUDED.due_at,
    assignee_id = EXCLUDED.assignee_id,
    parent_task_id = EXCLUDED.parent_task_id,
    updated_at = EXCLUDED.updated_at
RETURNING id, project_id, status_name, title, description, position, priority, due_at, assignee_id, parent_task_id, created_at, updated_at
`

type UpsertProjectTaskParams struct {
	ID           string             `json:"id"`
	ProjectID    string             `json:"project_id"`
	StatusName   string             `json:"status_name"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Position     int32              `json:"position"`
	Priority     int32              `json:"priority"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
	AssigneeID   pgtype.Text        `json:"assignee_id"`
	ParentTaskID pgtype.Text        `json:"parent_task_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertProjectTask(ctx context.Context, arg UpsertProjectTaskParams) (ProjectKanbanTask, error) {
	row := q.db.QueryRow(ctx, upsertProjectTask,
		arg.ID,
		arg.ProjectID,
		arg.StatusName,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.Priority,
		arg.DueAt,
		arg.AssigneeID,
		arg.ParentTaskID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProjectKanbanTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StatusName,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.DueAt,
		&i.AssigneeID,
		&i.ParentTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
