// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMemberBlueprint(ctx context.Context, arg AddMemberBlueprintParams) error
	CountRecordedMemberAttendanceAfterJoin(ctx context.Context, memberID string) (int32, error)
	CountUniqueAttendanceMembersSince(ctx context.Context, since pgtype.Timestamptz) (int32, error)
	DeleteAttendance(ctx context.Context, id string) error
	DeleteAttendancePayout(ctx context.Context, attendanceID string) error
	DeleteMember(ctx context.Context, id string) error
	GetAttendanceByID(ctx context.Context, id string) (Attendance, error)
	GetAttendancePayout(ctx context.Context, attendanceID string) (AttendancePayout, error)
	GetMember(ctx context.Context, id string) (Member, error)
	GetMemberIDs(ctx context.Context) ([]string, error)
	GetTokenBalances(ctx context.Context) ([]GetTokenBalancesRow, error)
	GetTokenByID(ctx context.Context, id string) (Token, error)
	InsertToken(ctx context.Context, arg InsertTokenParams) error
	ListActiveAttendance(ctx context.Context, limitRows int32) ([]Attendance, error)
	ListAllAttendance(ctx context.Context) ([]Attendance, error)
	ListAllTokens(ctx context.Context) ([]Token, error)
	ListAttendancePage(ctx context.Context, arg ListAttendancePageParams) ([]Attendance, error)
	ListAttendanceParticipants(ctx context.Context, attendanceID string) ([]AttendanceParticipant, error)
	ListMembersByBlueprint(ctx context.Context, blueprintID string) ([]Member, error)
	ListMembersByIDs(ctx context.Context, ids []string) ([]Member, error)
	ListMembersPage(ctx context.Context, arg ListMembersPageParams) ([]Member, error)
	ListRandomMembersByRank(ctx context.Context, arg ListRandomMembersByRankParams) ([]Member, error)
	ListRecordedAttendance(ctx context.Context, limitRows int32) ([]Attendance, error)
	ListTokensByAttendanceID(ctx context.Context, attendanceID pgtype.Text) ([]Token, error)
	ListTokensByMemberAndAttendance(ctx context.Context, arg ListTokensByMemberAndAttendanceParams) ([]Token, error)
	ListTokensSince(ctx context.Context, createdAfter pgtype.Timestamptz) ([]Token, error)
	ReplaceAttendanceParticipants(ctx context.Context, attendanceID string) error
	ReplaceMemberBlueprints(ctx context.Context, memberID string) error
	UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) error
	UpsertAttendanceParticipant(ctx context.Context, arg UpsertAttendanceParticipantParams) error
	UpsertAttendancePayout(ctx context.Context, arg UpsertAttendancePayoutParams) error
	UpsertMember(ctx context.Context, arg UpsertMemberParams) error
}

var _ Querier = (*Queries)(nil)
