// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMemberBlueprint(ctx context.Context, arg AddMemberBlueprintParams) error
	CountRecordedMemberAttendanceAfterJoin(ctx context.Context, memberID string) (int32, error)
	CountUniqueAttendanceMembersSince(ctx context.Context, since pgtype.Timestamptz) (int32, error)
	DeleteAllAttendanceNames(ctx context.Context) error
	DeleteAllAttendanceTags(ctx context.Context) error
	DeleteAttendance(ctx context.Context, id string) error
	DeleteAttendanceName(ctx context.Context, name string) error
	DeleteAttendanceParticipant(ctx context.Context, arg DeleteAttendanceParticipantParams) error
	DeleteAttendanceTag(ctx context.Context, tag string) error
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeleteRollEntriesByEvent(ctx context.Context, rollEventID string) error
	DeleteRollEntry(ctx context.Context, arg DeleteRollEntryParams) error
	DeleteRollEvent(ctx context.Context, id string) error
	DeleteRollItemsByEvent(ctx context.Context, rollEventID string) error
	GetAttendanceByID(ctx context.Context, id string) (Attendance, error)
	GetMember(ctx context.Context, id string) (GetMemberRow, error)
	GetMemberIDs(ctx context.Context) ([]string, error)
	GetRollEventByID(ctx context.Context, id string) (RollEvent, error)
	GetRsiInfoByHandle(ctx context.Context, handle string) (RsiInfo, error)
	GetTokenBalances(ctx context.Context) ([]GetTokenBalancesRow, error)
	GetTokenByID(ctx context.Context, id string) (Token, error)
	GetWeeklyCommandCounts(ctx context.Context) ([]GetWeeklyCommandCountsRow, error)
	InsertAttendanceName(ctx context.Context, name string) error
	InsertAttendanceTag(ctx context.Context, tag string) error
	InsertCommandLog(ctx context.Context, arg InsertCommandLogParams) error
	InsertToken(ctx context.Context, arg InsertTokenParams) error
	ListActiveAttendance(ctx context.Context, limitRows int32) ([]Attendance, error)
	ListActiveRollEvents(ctx context.Context, limitRows int32) ([]RollEvent, error)
	ListAllAttendance(ctx context.Context) ([]Attendance, error)
	ListAllTokens(ctx context.Context) ([]Token, error)
	ListAttendanceNames(ctx context.Context) ([]string, error)
	ListAttendancePage(ctx context.Context, arg ListAttendancePageParams) ([]Attendance, error)
	ListAttendanceParticipants(ctx context.Context, attendanceID string) ([]AttendanceParticipant, error)
	ListAttendanceTags(ctx context.Context) ([]string, error)
	ListMembersByBlueprint(ctx context.Context, blueprintID string) ([]ListMembersByBlueprintRow, error)
	ListMembersByIDs(ctx context.Context, ids []string) ([]ListMembersByIDsRow, error)
	ListMembersPage(ctx context.Context, arg ListMembersPageParams) ([]ListMembersPageRow, error)
	ListPromotions(ctx context.Context) ([]ListPromotionsRow, error)
	ListRandomMembersByRank(ctx context.Context, arg ListRandomMembersByRankParams) ([]ListRandomMembersByRankRow, error)
	ListRecordedAttendance(ctx context.Context, limitRows int32) ([]Attendance, error)
	ListRollEntriesByEvent(ctx context.Context, rollEventID string) ([]RollEntry, error)
	ListRollEntriesByItem(ctx context.Context, rollItemID string) ([]RollEntry, error)
	ListRollItemsByEvent(ctx context.Context, rollEventID string) ([]RollItem, error)
	ListRsiInfoByHandles(ctx context.Context, handles []string) ([]RsiInfo, error)
	ListTokensByAttendanceID(ctx context.Context, attendanceID pgtype.Text) ([]Token, error)
	ListTokensByMemberAndAttendance(ctx context.Context, arg ListTokensByMemberAndAttendanceParams) ([]Token, error)
	ListTokensSince(ctx context.Context, createdAfter pgtype.Timestamptz) ([]Token, error)
	MarkRollEventEnded(ctx context.Context, arg MarkRollEventEndedParams) error
	ReplaceMemberBlueprints(ctx context.Context, memberID string) error
	UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) error
	UpsertAttendanceParticipant(ctx context.Context, arg UpsertAttendanceParticipantParams) error
	UpsertBlueprintDoc(ctx context.Context, arg UpsertBlueprintDocParams) error
	UpsertKanbanCard(ctx context.Context, arg UpsertKanbanCardParams) error
	UpsertMember(ctx context.Context, arg UpsertMemberParams) error
	UpsertRollEntry(ctx context.Context, arg UpsertRollEntryParams) error
	UpsertRollEvent(ctx context.Context, arg UpsertRollEventParams) error
	UpsertRollItem(ctx context.Context, arg UpsertRollItemParams) error
	UpsertRsiInfo(ctx context.Context, arg UpsertRsiInfoParams) error
	UpsertSOSTicket(ctx context.Context, arg UpsertSOSTicketParams) error
}

var _ Querier = (*Queries)(nil)
