// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rolls.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRollEntriesByEvent = `-- name: DeleteRollEntriesByEvent :exec
DELETE FROM roll_entries
WHERE roll_event_id = $1
`

func (q *Queries) DeleteRollEntriesByEvent(ctx context.Context, rollEventID string) error {
	_, err := q.db.Exec(ctx, deleteRollEntriesByEvent, rollEventID)
	return err
}

const deleteRollEntry = `-- name: DeleteRollEntry :exec
DELETE FROM roll_entries
WHERE roll_item_id = $1
  AND member_id = $2
`

type DeleteRollEntryParams struct {
	RollItemID string `json:"roll_item_id"`
	MemberID   string `json:"member_id"`
}

func (q *Queries) DeleteRollEntry(ctx context.Context, arg DeleteRollEntryParams) error {
	_, err := q.db.Exec(ctx, deleteRollEntry, arg.RollItemID, arg.MemberID)
	return err
}

const deleteRollEvent = `-- name: DeleteRollEvent :exec
DELETE FROM roll_events
WHERE id = $1
`

func (q *Queries) DeleteRollEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRollEvent, id)
	return err
}

const deleteRollItemsByEvent = `-- name: DeleteRollItemsByEvent :exec
DELETE FROM roll_items
WHERE roll_event_id = $1
`

func (q *Queries) DeleteRollItemsByEvent(ctx context.Context, rollEventID string) error {
	_, err := q.db.Exec(ctx, deleteRollItemsByEvent, rollEventID)
	return err
}

const getRollEventByID = `-- name: GetRollEventByID :one
SELECT id, name, attendance_id, end_time, ended, channel_id, embed_message_id, input_message_id, created_at, updated_at
FROM roll_events
WHERE id = $1
`

func (q *Queries) GetRollEventByID(ctx context.Context, id string) (RollEvent, error) {
	row := q.db.QueryRow(ctx, getRollEventByID, id)
	var i RollEvent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AttendanceID,
		&i.EndTime,
		&i.Ended,
		&i.ChannelID,
		&i.EmbedMessageID,
		&i.InputMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRollEvents = `-- name: ListActiveRollEvents :many
SELECT id, name, attendance_id, end_time, ended, channel_id, embed_message_id, input_message_id, created_at, updated_at
FROM roll_events
WHERE ended = FALSE
ORDER BY created_at DESC
LIMIT $1::int
`

func (q *Queries) ListActiveRollEvents(ctx context.Context, limitRows int32) ([]RollEvent, error) {
	rows, err := q.db.Query(ctx, listActiveRollEvents, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollEvent
	for rows.Next() {
		var i RollEvent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AttendanceID,
			&i.EndTime,
			&i.Ended,
			&i.ChannelID,
			&i.EmbedMessageID,
			&i.InputMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollEntriesByEvent = `-- name: ListRollEntriesByEvent :many
SELECT roll_event_id, roll_item_id, member_id, choice, roll_value, winner, created_at, updated_at
FROM roll_entries
WHERE roll_event_id = $1
ORDER BY roll_item_id ASC, created_at ASC
`

func (q *Queries) ListRollEntriesByEvent(ctx context.Context, rollEventID string) ([]RollEntry, error) {
	rows, err := q.db.Query(ctx, listRollEntriesByEvent, rollEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollEntry
	for rows.Next() {
		var i RollEntry
		if err := rows.Scan(
			&i.RollEventID,
			&i.RollItemID,
			&i.MemberID,
			&i.Choice,
			&i.RollValue,
			&i.Winner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollEntriesByItem = `-- name: ListRollEntriesByItem :many
SELECT roll_event_id, roll_item_id, member_id, choice, roll_value, winner, created_at, updated_at
FROM roll_entries
WHERE roll_item_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRollEntriesByItem(ctx context.Context, rollItemID string) ([]RollEntry, error) {
	rows, err := q.db.Query(ctx, listRollEntriesByItem, rollItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollEntry
	for rows.Next() {
		var i RollEntry
		if err := rows.Scan(
			&i.RollEventID,
			&i.RollItemID,
			&i.MemberID,
			&i.Choice,
			&i.RollValue,
			&i.Winner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollItemsByEvent = `-- name: ListRollItemsByEvent :many
SELECT id, roll_event_id, name, amount, sort_order, channel_id, message_id, created_at
FROM roll_items
WHERE roll_event_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListRollItemsByEvent(ctx context.Context, rollEventID string) ([]RollItem, error) {
	rows, err := q.db.Query(ctx, listRollItemsByEvent, rollEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollItem
	for rows.Next() {
		var i RollItem
		if err := rows.Scan(
			&i.ID,
			&i.RollEventID,
			&i.Name,
			&i.Amount,
			&i.SortOrder,
			&i.ChannelID,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRollEventEnded = `-- name: MarkRollEventEnded :exec
UPDATE roll_events
SET ended = TRUE,
    updated_at = COALESCE($1, NOW())
WHERE id = $2
`

type MarkRollEventEndedParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

func (q *Queries) MarkRollEventEnded(ctx context.Context, arg MarkRollEventEndedParams) error {
	_, err := q.db.Exec(ctx, markRollEventEnded, arg.UpdatedAt, arg.ID)
	return err
}

const upsertRollEntry = `-- name: UpsertRollEntry :exec
INSERT INTO roll_entries (
    roll_event_id,
    roll_item_id,
    member_id,
    choice,
    roll_value,
    winner,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (roll_item_id, member_id) DO UPDATE
SET choice = EXCLUDED.choice,
    roll_value = EXCLUDED.roll_value,
    winner = EXCLUDED.winner,
    updated_at = EXCLUDED.updated_at
`

type UpsertRollEntryParams struct {
	RollEventID string             `json:"roll_event_id"`
	RollItemID  string             `json:"roll_item_id"`
	MemberID    string             `json:"member_id"`
	Choice      string             `json:"choice"`
	RollValue   pgtype.Int4        `json:"roll_value"`
	Winner      bool               `json:"winner"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertRollEntry(ctx context.Context, arg UpsertRollEntryParams) error {
	_, err := q.db.Exec(ctx, upsertRollEntry,
		arg.RollEventID,
		arg.RollItemID,
		arg.MemberID,
		arg.Choice,
		arg.RollValue,
		arg.Winner,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertRollEvent = `-- name: UpsertRollEvent :exec
INSERT INTO roll_events (
    id,
    name,
    attendance_id,
    end_time,
    ended,
    channel_id,
    embed_message_id,
    input_message_id,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    attendance_id = EXCLUDED.attendance_id,
    end_time = EXCLUDED.end_time,
    ended = EXCLUDED.ended,
    channel_id = EXCLUDED.channel_id,
    embed_message_id = EXCLUDED.embed_message_id,
    input_message_id = EXCLUDED.input_message_id,
    updated_at = EXCLUDED.updated_at
`

type UpsertRollEventParams struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	AttendanceID   pgtype.Text        `json:"attendance_id"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Ended          bool               `json:"ended"`
	ChannelID      string             `json:"channel_id"`
	EmbedMessageID string             `json:"embed_message_id"`
	InputMessageID string             `json:"input_message_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertRollEvent(ctx context.Context, arg UpsertRollEventParams) error {
	_, err := q.db.Exec(ctx, upsertRollEvent,
		arg.ID,
		arg.Name,
		arg.AttendanceID,
		arg.EndTime,
		arg.Ended,
		arg.ChannelID,
		arg.EmbedMessageID,
		arg.InputMessageID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertRollItem = `-- name: UpsertRollItem :exec
INSERT INTO roll_items (
    id,
    roll_event_id,
    name,
    amount,
    sort_order,
    channel_id,
    message_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (id) DO UPDATE
SET roll_event_id = EXCLUDED.roll_event_id,
    name = EXCLUDED.name,
    amount = EXCLUDED.amount,
    sort_order = EXCLUDED.sort_order
`

type UpsertRollItemParams struct {
	ID          string             `json:"id"`
	RollEventID string             `json:"roll_event_id"`
	Name        string             `json:"name"`
	Amount      int32              `json:"amount"`
	SortOrder   int32              `json:"sort_order"`
	ChannelID   pgtype.Text        `json:"channel_id"`
	MessageID   pgtype.Text        `json:"message_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertRollItem(ctx context.Context, arg UpsertRollItemParams) error {
	_, err := q.db.Exec(ctx, upsertRollItem,
		arg.ID,
		arg.RollEventID,
		arg.Name,
		arg.Amount,
		arg.SortOrder,
		arg.ChannelID,
		arg.MessageID,
		arg.CreatedAt,
	)
	return err
}
