// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rsi_info.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRsiInfoByHandle = `-- name: GetRsiInfoByHandle :one
SELECT handle, primary_org, primary_org_sid, affiliations FROM rsi_info WHERE handle = $1
`

func (q *Queries) GetRsiInfoByHandle(ctx context.Context, handle string) (RsiInfo, error) {
	row := q.db.QueryRow(ctx, getRsiInfoByHandle, handle)
	var i RsiInfo
	err := row.Scan(
		&i.Handle,
		&i.PrimaryOrg,
		&i.PrimaryOrgSid,
		&i.Affiliations,
	)
	return i, err
}

const listRsiInfoByHandles = `-- name: ListRsiInfoByHandles :many
SELECT handle, primary_org, primary_org_sid, affiliations FROM rsi_info WHERE handle = ANY($1::text[])
`

func (q *Queries) ListRsiInfoByHandles(ctx context.Context, handles []string) ([]RsiInfo, error) {
	rows, err := q.db.Query(ctx, listRsiInfoByHandles, handles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RsiInfo
	for rows.Next() {
		var i RsiInfo
		if err := rows.Scan(
			&i.Handle,
			&i.PrimaryOrg,
			&i.PrimaryOrgSid,
			&i.Affiliations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRsiInfo = `-- name: UpsertRsiInfo :exec
INSERT INTO rsi_info (handle, primary_org, primary_org_sid, affiliations)
VALUES ($1, $2, $3, $4)
ON CONFLICT (handle) DO UPDATE
SET primary_org = EXCLUDED.primary_org,
    primary_org_sid = EXCLUDED.primary_org_sid,
    affiliations = EXCLUDED.affiliations
`

type UpsertRsiInfoParams struct {
	Handle        string      `json:"handle"`
	PrimaryOrg    pgtype.Text `json:"primary_org"`
	PrimaryOrgSid pgtype.Text `json:"primary_org_sid"`
	Affiliations  []string    `json:"affiliations"`
}

func (q *Queries) UpsertRsiInfo(ctx context.Context, arg UpsertRsiInfoParams) error {
	_, err := q.db.Exec(ctx, upsertRsiInfo,
		arg.Handle,
		arg.PrimaryOrg,
		arg.PrimaryOrgSid,
		arg.Affiliations,
	)
	return err
}
