// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTokenBalances = `-- name: GetTokenBalances :many
SELECT member_id,
       SUM(amount)::int AS balance
FROM tokens
GROUP BY member_id
ORDER BY member_id
`

type GetTokenBalancesRow struct {
	MemberID string `json:"member_id"`
	Balance  int32  `json:"balance"`
}

func (q *Queries) GetTokenBalances(ctx context.Context) ([]GetTokenBalancesRow, error) {
	rows, err := q.db.Query(ctx, getTokenBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTokenBalancesRow
	for rows.Next() {
		var i GetTokenBalancesRow
		if err := rows.Scan(&i.MemberID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, member_id, amount, reason, attendance_id, comment, giver_id, created_at
FROM tokens
WHERE id = $1
`

func (q *Queries) GetTokenByID(ctx context.Context, id string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByID, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Amount,
		&i.Reason,
		&i.AttendanceID,
		&i.Comment,
		&i.GiverID,
		&i.CreatedAt,
	)
	return i, err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO tokens (
    id,
    member_id,
    amount,
    reason,
    attendance_id,
    comment,
    giver_id,
  created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
  $8
)
`

type InsertTokenParams struct {
	ID           string             `json:"id"`
	MemberID     string             `json:"member_id"`
	Amount       int32              `json:"amount"`
	Reason       string             `json:"reason"`
	AttendanceID pgtype.Text        `json:"attendance_id"`
	Comment      pgtype.Text        `json:"comment"`
	GiverID      pgtype.Text        `json:"giver_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.Exec(ctx, insertToken,
		arg.ID,
		arg.MemberID,
		arg.Amount,
		arg.Reason,
		arg.AttendanceID,
		arg.Comment,
		arg.GiverID,
		arg.CreatedAt,
	)
	return err
}

const listAllTokens = `-- name: ListAllTokens :many
SELECT id, member_id, amount, reason, attendance_id, comment, giver_id, created_at
FROM tokens
ORDER BY created_at DESC
`

func (q *Queries) ListAllTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.Query(ctx, listAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Amount,
			&i.Reason,
			&i.AttendanceID,
			&i.Comment,
			&i.GiverID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByMemberId = `-- name: ListByMemberId :many
SELECT id, member_id, amount, reason, attendance_id, comment, giver_id, created_at
FROM tokens
WHERE member_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListByMemberId(ctx context.Context, memberID string) ([]Token, error) {
	rows, err := q.db.Query(ctx, listByMemberId, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Amount,
			&i.Reason,
			&i.AttendanceID,
			&i.Comment,
			&i.GiverID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByAttendanceID = `-- name: ListTokensByAttendanceID :many
SELECT id, member_id, amount, reason, attendance_id, comment, giver_id, created_at
FROM tokens
WHERE attendance_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTokensByAttendanceID(ctx context.Context, attendanceID pgtype.Text) ([]Token, error) {
	rows, err := q.db.Query(ctx, listTokensByAttendanceID, attendanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Amount,
			&i.Reason,
			&i.AttendanceID,
			&i.Comment,
			&i.GiverID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByMemberAndAttendance = `-- name: ListTokensByMemberAndAttendance :many
SELECT id, member_id, amount, reason, attendance_id, comment, giver_id, created_at
FROM tokens
WHERE member_id = $1
  AND attendance_id = $2
ORDER BY created_at DESC
`

type ListTokensByMemberAndAttendanceParams struct {
	MemberID     string      `json:"member_id"`
	AttendanceID pgtype.Text `json:"attendance_id"`
}

func (q *Queries) ListTokensByMemberAndAttendance(ctx context.Context, arg ListTokensByMemberAndAttendanceParams) ([]Token, error) {
	rows, err := q.db.Query(ctx, listTokensByMemberAndAttendance, arg.MemberID, arg.AttendanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Amount,
			&i.Reason,
			&i.AttendanceID,
			&i.Comment,
			&i.GiverID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensSince = `-- name: ListTokensSince :many
SELECT id, member_id, amount, reason, attendance_id, comment, giver_id, created_at
FROM tokens
WHERE created_at > $1
ORDER BY created_at ASC
`

func (q *Queries) ListTokensSince(ctx context.Context, createdAfter pgtype.Timestamptz) ([]Token, error) {
	rows, err := q.db.Query(ctx, listTokensSince, createdAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Amount,
			&i.Reason,
			&i.AttendanceID,
			&i.Comment,
			&i.GiverID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
